version: 0.1
default:
  deploy:
    parameters:
      stack_name: serverless-etl-s3-to-iceberg
      region: us-east-2
      resolve_s3: true
      profile: default
      capabilities:
        - CAPABILITY_NAMED_IAM
      parameter_overrides:
        - PrincipalOrgId=
        - LoggingBucketName=
      tags:
        - app=serverless-etl-s3-to-iceberg
